apiVersion: v1
kind: Service
metadata:
  name: demoprojectservice
spec:
  type: NodePort
  selector:
    app: demoproject
  ports:
    - protocol: TCP
      nodePort: 30082
      port: 9999
      targetPort: 9999