apiVersion: v1
kind: Service
metadata:
  name: demoprojectservice
spec:
  type: NodePort
  selector:
    app: demoproject
  ports:
    - protocol: TCP
      nodePort: 30082
      port: 8080
      targetPort: 8080